# Generated by Django 3.2.3 on 2021-06-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
